use super::*;

/// Does the user who sent this member event have required power levels to do
/// so.
///
/// * `user` - Information about the membership event and user making the
///   request.
/// * `auth_events` - The set of auth events that relate to a membership event.
///
/// This is generated by calling `auth_types_for_event` with the membership
/// event and the current State.
#[allow(clippy::too_many_arguments)]
#[allow(clippy::cognitive_complexity)]
pub(super) fn valid_membership_change(
    room_version: &RoomVersion,
    target_user: &UserId,
    target_user_membership_event: Option<&impl Event>,
    sender: &UserId,
    sender_membership_event: Option<&impl Event>,
    current_event: impl Event,
    current_third_party_invite: Option<&impl Event>,
    power_levels_event: Option<&impl Event>,
    join_rules_event: Option<&impl Event>,
    user_for_join_auth: Option<&UserId>,
    user_for_join_auth_membership: &MembershipState,
    create_room: &impl Event,
) -> Result<bool> {
    #[derive(Deserialize)]
    struct GetThirdPartyInvite {
        third_party_invite: Option<Raw<ThirdPartyInvite>>,
    }
    let content = current_event.content();

    let target_membership = from_json_str::<GetMembership>(content.get())?.membership;
    let third_party_invite =
        from_json_str::<GetThirdPartyInvite>(content.get())?.third_party_invite;

    let sender_membership = match &sender_membership_event {
        Some(pdu) => from_json_str::<GetMembership>(pdu.content().get())?.membership,
        None => MembershipState::Leave,
    };
    let sender_is_joined = sender_membership == MembershipState::Join;

    let target_user_current_membership = match &target_user_membership_event {
        Some(pdu) => from_json_str::<GetMembership>(pdu.content().get())?.membership,
        None => MembershipState::Leave,
    };

    let power_levels: RoomPowerLevelsEventContent = match &power_levels_event {
        Some(ev) => from_json_str(ev.content().get())?,
        None => from_json_str("{}")?,
    };

    let sender_power = power_levels
        .users
        .get(sender)
        .or_else(|| sender_is_joined.then_some(&power_levels.users_default));

    let target_power = power_levels.users.get(target_user).or_else(|| {
        (target_membership == MembershipState::Join).then_some(&power_levels.users_default)
    });

    let mut join_rules = JoinRule::Invite;
    if let Some(jr) = &join_rules_event {
        join_rules = from_json_str::<RoomJoinRulesEventContent>(jr.content().get())?.join_rule;
    }

    let power_levels_event_id = power_levels_event.as_ref().map(Event::event_id);
    let sender_membership_event_id = sender_membership_event.as_ref().map(Event::event_id);
    let target_user_membership_event_id =
        target_user_membership_event.as_ref().map(Event::event_id);

    let user_for_join_auth_is_valid = if let Some(user_for_join_auth) = user_for_join_auth {
        let (auth_user_pl, invite_level) = if let Some(pl) = &power_levels_event {
            let invite =
                deserialize_power_levels_content_invite(pl.content().get(), room_version)?.invite;

            let content =
                deserialize_power_levels_content_fields(pl.content().get(), room_version)?;
            let user_pl = match content.get_user_power(user_for_join_auth) {
                Some(level) => *level,
                _ => content.users_default,
            };

            (user_pl, invite)
        } else {
            (int!(0), int!(0))
        };
        (user_for_join_auth_membership == &MembershipState::Join) && (auth_user_pl >= invite_level)
    } else {
        false
    };

    Ok(match target_membership {
        MembershipState::Join => {
            let mut prev_events = current_event.prev_events();

            let prev_event_is_create_event = prev_events
                .next()
                .is_some_and(|event_id| event_id.borrow() == create_room.event_id().borrow());
            let no_more_prev_events = prev_events.next().is_none();

            if prev_event_is_create_event && no_more_prev_events {
                let is_creator = if room_version.use_room_create_sender {
                    let creator = create_room.sender();

                    creator == sender && creator == target_user
                } else {
                    #[allow(deprecated)]
                    let creator =
                        from_json_str::<RoomCreateEventContent>(create_room.content().get())?
                            .creator
                            .ok_or_else(|| serde_json::Error::missing_field("creator"))?;

                    creator == sender && creator == target_user
                };

                if is_creator {
                    return Ok(true);
                }
            }

            if sender != target_user {
                warn!("Can't make other user join");
                false
            } else if target_user_current_membership == MembershipState::Ban {
                warn!(?target_user_membership_event_id, "Banned user can't join");
                false
            } else if (join_rules == JoinRule::Invite
                || room_version.allow_knocking && join_rules == JoinRule::Knock)
                && (target_user_current_membership == MembershipState::Join
                    || target_user_current_membership == MembershipState::Invite)
            {
                true
            } else if room_version.restricted_join_rules
                && matches!(join_rules, JoinRule::Restricted(_))
                || room_version.knock_restricted_join_rule
                    && matches!(join_rules, JoinRule::KnockRestricted(_))
            {
                if matches!(
                    target_user_current_membership,
                    MembershipState::Invite | MembershipState::Join
                ) {
                    true
                } else {
                    user_for_join_auth_is_valid
                }
            } else {
                join_rules == JoinRule::Public
            }
        }
        MembershipState::Invite => match third_party_invite.and_then(|i| i.deserialize().ok()) {
            Some(tp_id) => {
                if target_user_current_membership == MembershipState::Ban {
                    warn!(?target_user_membership_event_id, "Can't invite banned user");
                    false
                } else {
                    let allow = verify_third_party_invite(
                        Some(target_user),
                        sender,
                        &tp_id,
                        current_third_party_invite,
                    );
                    if !allow {
                        warn!("Third party invite invalid");
                    }
                    allow
                }
            }
            _ => {
                if !sender_is_joined
                    || target_user_current_membership == MembershipState::Join
                    || target_user_current_membership == MembershipState::Ban
                {
                    warn!(
                        ?target_user_membership_event_id,
                        ?sender_membership_event_id,
                        "Can't invite user if sender not joined or the user is currently \
							 joined or banned",
                    );
                    false
                } else {
                    let allow = sender_power
                        .filter(|&p| p >= &power_levels.invite)
                        .is_some();
                    if !allow {
                        warn!(
                            ?target_user_membership_event_id,
                            ?power_levels_event_id,
                            "User does not have enough power to invite",
                        );
                    }
                    allow
                }
            }
        },
        MembershipState::Leave => {
            if sender == target_user {
                let allow = target_user_current_membership == MembershipState::Join
                    || target_user_current_membership == MembershipState::Invite
                    || target_user_current_membership == MembershipState::Knock;
                if !allow {
                    warn!(
                        ?target_user_membership_event_id,
                        ?target_user_current_membership,
                        "Can't leave if sender is not already invited, knocked, or joined"
                    );
                }
                allow
            } else if !sender_is_joined
                || target_user_current_membership == MembershipState::Ban
                    && sender_power.filter(|&p| p < &power_levels.ban).is_some()
            {
                warn!(
                    ?target_user_membership_event_id,
                    ?sender_membership_event_id,
                    "Can't kick if sender not joined or user is already banned",
                );
                false
            } else {
                let allow = sender_power.filter(|&p| p >= &power_levels.kick).is_some()
                    && target_power < sender_power;
                if !allow {
                    warn!(
                        ?target_user_membership_event_id,
                        ?power_levels_event_id,
                        "User does not have enough power to kick",
                    );
                }
                allow
            }
        }
        MembershipState::Ban => {
            if !sender_is_joined {
                warn!(
                    ?sender_membership_event_id,
                    "Can't ban user if sender is not joined"
                );
                false
            } else {
                let allow = sender_power.filter(|&p| p >= &power_levels.ban).is_some()
                    && target_power < sender_power;
                if !allow {
                    warn!(
                        ?target_user_membership_event_id,
                        ?power_levels_event_id,
                        "User does not have enough power to ban",
                    );
                }
                allow
            }
        }
        MembershipState::Knock if room_version.allow_knocking => {
            if !matches!(join_rules, JoinRule::KnockRestricted(_) | JoinRule::Knock) {
                warn!("Join rule is not set to knock or knock_restricted, knocking is not allowed");
                false
            } else if matches!(join_rules, JoinRule::KnockRestricted(_))
                && !room_version.knock_restricted_join_rule
            {
                warn!(
                    "Join rule is set to knock_restricted but room version does not support \
					 knock_restricted, knocking is not allowed"
                );
                false
            } else if sender != target_user {
                warn!(
                    ?sender,
                    ?target_user,
                    "Can't make another user knock, sender did not match target"
                );
                false
            } else if matches!(
                sender_membership,
                MembershipState::Ban | MembershipState::Invite | MembershipState::Join
            ) {
                warn!(
                    ?target_user_membership_event_id,
                    "Knocking with a membership state of ban, invite or join is invalid",
                );
                false
            } else {
                true
            }
        }
        _ => {
            warn!("Unknown membership transition");
            false
        }
    })
}

fn verify_third_party_invite(
    target_user: Option<&UserId>,
    sender: &UserId,
    tp_id: &ThirdPartyInvite,
    current_third_party_invite: Option<impl Event>,
) -> bool {
    #[allow(clippy::manual_let_else)]
    let signed = match tp_id.signed.deserialize() {
        Ok(signed) => signed,
        Err(_) => return false,
    };

    if target_user != Some(&signed.mxid) {
        return false;
    }

    #[allow(clippy::manual_let_else)]
    let current_tpid = match current_third_party_invite {
        Some(id) => id,
        None => return false,
    };

    if current_tpid.state_key() != Some(signed.token.as_str()) {
        return false;
    }

    if sender != current_tpid.sender() {
        return false;
    }

    #[allow(clippy::manual_let_else)]
    let tpid_ev =
        match from_json_str::<RoomThirdPartyInviteEventContent>(current_tpid.content().get()) {
            Ok(ev) => ev,
            Err(_) => return false,
        };

    #[allow(clippy::manual_let_else)]
    let decoded_invite_token = match Base64::<Standard>::parse(&signed.token) {
        Ok(tok) => tok.into_inner(),
        Err(_) => return false,
    };

    let matches_token = |key: &IdentityServerBase64PublicKey| {
        key.decode().is_ok_and(|key| key == decoded_invite_token)
    };

    for key in tpid_ev.public_keys.unwrap_or_default() {
        if matches_token(&key.public_key) {
            return true;
        }
    }

    matches_token(&tpid_ev.public_key)
}
