### phantom configuration
###
### THIS FILE IS GENERATED. CHANGES/CONTRIBUTIONS IN THE REPO WILL BE
### OVERWRITTEN!
###
### You should rename this file before configuring your server. Changes to
### documentation and defaults can be contributed in source code at
### crates/phantom-core/src/config/mod.rs. This file is generated when
### building.
###
### Any values pre-populated are the default values for said config option.

[global]

# The server_name is the pretty name of this server. It is used as a
# suffix for user and room IDs/aliases.
#
# YOU NEED TO EDIT THIS. THIS CANNOT BE CHANGED AFTER WITHOUT A DATABASE
# WIPE.
#
# example: "phantom.chat"
#
#server_name =

# The default address (IPv4 or IPv6) phantom will listen on.
#
# To listen on multiple addresses, specify a vector e.g. ["127.0.0.1",
# "::1"]
#
#address = ["127.0.0.1", "::1"]

# The port(s) phantom will listen on.
#
# To listen on multiple ports, specify a vector e.g. [8080, 8448]
#
#port = 8008

# Path to the directory holding the database.
#
# YOU NEED TO EDIT THIS.
#
# example: "/var/lib/phantom"
#
#database_path =

# Enable the built-in metrics endpoint.
#
#allow_metrics = false

# Max log level for phantom. Allows debug, info, warn, or error.
#
# See also:
# https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
#
# **Caveat**:
# For release builds, the tracing crate is configured to only implement
# levels higher than error to avoid unnecessary overhead in the compiled
# binary from trace macros. For debug builds, this restriction is not
# applied.
#
#log = "info"

# Output logs with ANSI colours. Colours are omitted regardless of this
# setting when running under systemd, where they would be stored verbatim
# in the journal.
#
#log_colors = true

# Configures the span events which will be outputted with the log.
#
# Accepts one or more of "new", "enter", "exit", "close", "active",
# "full" or "none", separated by commas.
#
#log_span_events = "none"

# Configures whether `log` matches values using regular expressions. See
# the tracing_subscriber documentation on Directives.
#
#log_filter_regex = true

# Toggles the display of ThreadId in tracing log output.
#
#log_thread_ids = false

# A shared secret required to register an account.
#
#registration_token =
